name: Build and Upload Artifact

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      continue-on-error: true
      
    - name: Build with Gradle
      run: |
        if [ -f "./gradlew" ]; then
          ./gradlew build shadowJar --no-daemon
        else
          gradle build shadowJar --no-daemon
        fi
        
    - name: List build outputs
      run: |
        echo "Build directory contents:"
        find build -name "*.jar" -type f 2>/dev/null || true
        echo "Project root jar files:"
        find . -maxdepth 2 -name "*.jar" -type f 2>/dev/null || true
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: elitemobs-${{ github.event_name }}-${{ github.run_number }}
        path: |
          build/libs/*.jar
          testbed/plugins/*.jar
        retention-days: 30
        if-no-files-found: warn
        
    - name: Upload shadowJar specifically (if exists)
      uses: actions/upload-artifact@v4
      with:
        name: elitemobs-shadowjar-${{ github.event_name }}-${{ github.run_number }}
        path: |
          build/libs/EliteMobs.jar
          testbed/plugins/EliteMobs.jar
        retention-days: 30
        if-no-files-found: ignore